import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/Header";
import { sanityClient, urlFor } from "../sanity";

export default function Home({ posts }) {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Medium - clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* Banner */}
      <div className="px-10 space-y-5 flex items-center justify-between bg-yellow-400 border-y border-black py-10 lg:py-0">
        <div>
          <h1 className="text-6xl font-serif max-w-xl mb-3">
            <span className="underline font-serif decoration-4"> Medium</span>{" "}
            is a place to read, write & connect
          </h1>
          <p>
            It's easy and free to post your thinking on any topic and connect
            with millions of readers
          </p>
        </div>
        <h1 className=" hidden md:inline-flex logo ">M</h1>
      </div>

      {/* Posts */}

      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 md:gap-6 p-2">
        {posts.map((post) => (
          <Link key={post._id} href={`/post/${post.slug.current}`}>
            <div className="border rounded-lg overflow-hidden  cursor-pointer group">
              <img
                className="w-full h-60 object-contain group-hover:scale-105 transition-transform duration-200 ease-in-out"
                src={urlFor(post.mainImage).url()}
                alt=""
              />
              <div className="flex justify-between p-5 bg-white">
                <div>
                  <p className="font-bold">{post.title}</p>
                  <p className="text-xs">By {post.author.name}</p>
                </div>
                <img
                  className="h-12 w-12 rounded-full"
                  src={urlFor(post.author.image).url()}
                  alt=""
                />
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author-> {
    name,
    image
    
  },
  mainImage,
  slug
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
